In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
def date_lapse(df, date_names=["ActivityDay", "SleepDay", "ActivityDate", "Date"], lapse_name="lapse"):
    # return a df with a new column called "lapse" (or as specified)
    name = np.array(df.columns)[[i in date_names for i in df.columns]][0]
    df[name] = pd.to_datetime(df[name])
    start_dates = {}
    for id, frame in df.sort_values(by=name).groupby("Id"):
        start_dates[id] = frame.iloc[0][name]
    df[lapse_name] = [(row[name] - start_dates[row["Id"]]).days  for _, row in df.iterrows()]
    return df

In [3]:
processed_data_dir = "ProcessedData"
data_dir = "Data"
df = pd.read_csv(os.path.join(processed_data_dir,"dailyActivity_weight_merged.csv"),index_col=0)
df = date_lapse(df)
df.head()

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,BMI,WeightKg,lapse
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.0,25,13,328,728,1985,25.487083,85.145834,0
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.0,21,19,217,776,1797,25.487083,85.145834,1
2,1503960366,2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.0,30,11,181,1218,1776,25.487083,85.145834,2
3,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.0,29,34,209,726,1745,25.487083,85.145834,3
4,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.0,36,10,221,773,1863,25.487083,85.145834,4

In [12]:
x_vars = list(df.columns)
x_vars.remove('Id')
x_vars

['ActivityDate',
 'TotalSteps',
 'TotalDistance',
 'TrackerDistance',
 'LoggedActivitiesDistance',
 'VeryActiveDistance',
 'ModeratelyActiveDistance',
 'LightActiveDistance',
 'SedentaryActiveDistance',
 'VeryActiveMinutes',
 'FairlyActiveMinutes',
 'LightlyActiveMinutes',
 'SedentaryMinutes',
 'Calories',
 'BMI',
 'WeightKg',
 'lapse']

In [13]:
df['Id'].unique()

array([1503960366, 1624580081, 1644430081, 1844505072, 1927972279,
       2022484408, 2026352035, 2320127002, 2347167796, 2873212765,
       3372868164, 3977333714, 4020332650, 4057192912, 4319703577,
       4388161847, 4445114986, 4558609924, 4702921684, 5553957443,
       5577150313, 6117666160, 6290855005, 6775888955, 6962181067,
       7007744171, 7086361926, 8053475328, 8253242879, 8378563200,
       8583815059, 8792009665, 8877689391])

In [15]:
idxs = [1503960366, 1624580081]
df[df['Id'].isin(idxs)]

,Id,ActivityDate,TotalSteps,TotalDistance,TrackerDistance,LoggedActivitiesDistance,VeryActiveDistance,ModeratelyActiveDistance,LightActiveDistance,SedentaryActiveDistance,VeryActiveMinutes,FairlyActiveMinutes,LightlyActiveMinutes,SedentaryMinutes,Calories,BMI,WeightKg,lapse
0,1503960366,2016-04-12,13162,8.50,8.50,0.0,1.88,0.55,6.06,0.00,25,13,328,728,1985,25.487083,85.145834,0
1,1503960366,2016-04-13,10735,6.97,6.97,0.0,1.57,0.69,4.71,0.00,21,19,217,776,1797,25.487083,85.145834,1
2,1503960366,2016-04-14,10460,6.74,6.74,0.0,2.44,0.40,3.91,0.00,30,11,181,1218,1776,25.487083,85.145834,2
3,1503960366,2016-04-15,9762,6.28,6.28,0.0,2.14,1.26,2.83,0.00,29,34,209,726,1745,25.487083,85.145834,3
4,1503960366,2016-04-16,12669,8.16,8.16,0.0,2.71,0.41,5.04,0.00,36,10,221,773,1863,25.487083,85.145834,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,1624580081,2016-05-08,3427,2.23,2.23,0.0,0.00,0.00,2.22,0.00,0,0,152,1288,1427,25.487083,85.145834,26
58,1624580081,2016-05-09,1732,1.13,1.13,0.0,0.00,0.00,1.13,0.00,0,0,91,1349,1328,25.487083,85.145834,27
59,1624580081,2016-05-10,2969,1.93,1.93,0.0,0.00,0.00,1.92,0.01,0,0,139,1301,1393,25.487083,85.145834,28
60,1624580081,2016-05-11,3134,2.04,2.04,0.0,0.00,0.00,2.04,0.00,0,0,112,1328,1359,25.487083,85.145834,29
61,1624580081,2016-05-12,2971,1.93,1.93,0.0,0.00,0.00,1.92,0.01,0,0,107,890,1002,25.487083,85.145834,30